# This is a basic workflow that is manually triggered

name: Manual Test Apis

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Run API TESTS
      run: |
        python scripts/quickApiChecks.py
      env:
        # SECRETS_CONTEXT: ${{ toJson(secrets) }}
        BITQUERY_API_KEY: ${{secrets.BITQUERY_API_KEY}}
        ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
        BSCSCAN_API_KEY: ${{secrets.BSCSCAN_API_KEY}}
        ETHPLORER_API_KEY: ${{secrets.ETHPLORER_API_KEY}}
        ETH_QUIKNODE_API_KEY: ${{secrets.ETH_QUIKNODE_API_KEY}}
        BSC_API_KEY: ${{secrets.BSC_API_KEY}}
        FIREBASE_PW_FOR_TESTS: ${{secrets.FIREBASE_PW_FOR_TESTS}}
        FIREBASE_USER_FOR_TESTS: ${{secrets.FIREBASE_USER_FOR_TESTS}}
        FIREBASE_WEB_API_KEY: ${{secrets.FIREBASE_WEB_API_KEY}}
        MONGODB_SRV: ${{secrets.MONGODB_SRV}}
        SENTRY_DSN: ${{secrets.SENTRY_DSN}}
        BACKOFFICE_APP_URL: ${{secrets.BACKOFFICE_APP_URL}}
        SENTRY_ENVIRONMENT: 'dev'

